export const CONSTANTS = {
    SIGNUP_START: 'SIGNUP_START',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    GET_NEWS_START: 'GET_NEWS_START',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
    GET_NEWS_ERROR: 'GET_NEWS_ERROR',

    ADD_NEWS_START: 'ADD_NEWS_START',
    ADD_NEWS_SUCCESS: 'ADD_NEWS_SUCCESS',
    ADD_NEWS_ERROR: 'ADD_NEWS_ERROR',
    
    UPDATE_NEWS_ERROR: 'UPDATE_NEWS_ERROR',

    DELETE_NEWS_START: 'DELETE_NEWS_START',
    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_ERROR: 'DELETE_NEWS_ERROR',

    GET_CURRENT_NEWS_START: 'GET_CURRENT_NEWS_START',
    GET_CURRENT_NEWS_SUCCESS: 'GET_CURRENT_NEWS_SUCCESS',
    GET_CURRENT_NEWS_ERROR: 'GET_CURRENT_NEWS_ERROR',

    SET_ADMIN_ID_IN_STORE: 'SET_ADMIN_ID_IN_STORE',
    
    GET_ADMIN_START: 'GET_ADMIN_START',
    GET_ADMIN_SUCCESS: 'GET_ADMIN_SUCCESS',
    GET_ADMIN_ERROR: 'GET_ADMIN_ERROR',

    GET_ADMINS_START: 'GET_ADMINS_START',
    GET_ADMINS_SUCCESS: 'GET_ADMINS_SUCCESS',
    GET_ADMINS_ERROR: 'GET_ADMINS_ERROR',

    UPDATE_ADMIN_START: 'UPDATE_ADMIN_START',
    UPDATE_ADMIN_SUCCESS: 'UPDATE_ADMIN_SUCCESS',
    UPDATE_ADMIN_ERROR: 'UPDATE_ADMIN_ERROR',

    DELETE_ADMIN_START: 'DELETE_ADMIN_START',
    DELETE_ADMIN_SUCCESS: 'DELETE_ADMIN_SUCCESS',
    DELETE_ADMIN_ERROR: 'DELETE_ADMIN_ERROR',

    LOGOUT: 'LOGOUT',

    SEND_INVITATION_START: 'SEND_INVITATION_START',
    SEND_INVITATION_SUCCESS: 'SEND_INVITATION_SUCCESS',
    SEND_INVITATION_ERROR: 'SEND_INVITATION_ERROR',

    GET_INVITATION_DATA_START: 'GET_INVITATION_DATA_START',
    GET_INVITATION_DATA_SUCCESS: 'GET_INVITATION_DATA_SUCCESS',
    GET_INVITATION_DATA_ERROR: 'GET_INVITATION_DATA_ERROR',

    GET_NEWS_TYPES_START: 'GET_NEWS_TYPES_START',
    GET_NEWS_TYPES_SUCCESS: 'GET_NEWS_TYPES_SUCCESS',
    GET_NEWS_TYPES_ERROR: 'GET_NEWS_TYPES_ERROR',
    
    GET_CURRENT_IMAGE_START: 'GET_CURRENT_IMAGE_START',
    GET_CURRENT_IMAGE_SUCCESS: 'GET_CURRENT_IMAGE_SUCCESS',
    GET_CURRENT_IMAGE_ERROR: 'GET_CURRENT_IMAGE_ERROR',

    GET_MYNEWS_START: 'GET_MYNEWS_START',
    GET_MYNEWS_SUCCESS: 'GET_MYNEWS_SUCCESS',
    GET_MYNEWS_ERROR: 'GET_MYNEWS_ERROR',

    ATTACH_ADMIN_TO_NEWS_START: 'ATTACH_ADMIN_TO_NEWS_START',
    ATTACH_ADMIN_TO_NEWS_SUCCESS: 'ATTACH_ADMIN_TO_NEWS_SUCCESS',
    ATTACH_ADMIN_TO_NEWS_ERROR: 'ATTACH_ADMIN_TO_NEWS_ERROR',
    
    GET_ATTACHED_ADMINS_START: 'GET_ATTACHED_ADMINS_START',
    GET_ATTACHED_ADMINS_SUCCESS: 'GET_ATTACHED_ADMINS_SUCCESS',
    GET_ATTACHED_ADMINS_ERROR: 'GET_ATTACHED_ADMINS_ERROR',

    SHOW_MODAL: 'SHOW_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    
    SEND_DATA_FOR_PDF_START: 'SEND_DATA_FOR_PDF_START',
    SEND_DATA_FOR_PDF_SUCCESS: 'SEND_DATA_FOR_PDF_SUCCESS',
    SEND_DATA_FOR_PDF_ERROR: 'SEND_DATA_FOR_PDF_ERROR',

    DELETE_IMAGE_START: 'DELETE_IMAGE_START',
    DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
    DELETE_IMAGE_ERROR: 'DELETE_IMAGE_ERROR',

    CLEAR_MESSAGES: 'CLEAR_MESSAGES'

}